### ISSUE TITLE
Option to include sprite size in generated css

### ISSUE THREAD

**Issue by F21** [glebmachine/postcss-easysprites#11]
If I have the following css:

``` css
.facebook{
    background-image: url('./test.png#sprites');
}
```

The following is generated:

``` css
.facebook{
    background-image: url(51e83fd2b1c443620524b9c2c8fa29db.png); background-position: -1707px 0;
}
```

However, to get it to display correctly, I need to manually add the size of the sprite into the original css:

``` css
.facebook{
    background-image: url('./test.png#sprites');
    width: 100px;
    height: 100px;
}
```

It would be nice if the generated css output automatically included the size (via an option):

``` css
.facebook{
    background-image: url(51e83fd2b1c443620524b9c2c8fa29db.png); background-position: -1707px 0;
    width: 100px;
    height: 100px;
}
```
