### ISSUE TITLE
Better background-color support

### ISSUE THREAD

**Issue by cahnory** [glebmachine/postcss-easysprites#13]
If you use named color (and looking the sources, hsl(a) ones too) they are removed.

``` css
/* source */
.foo {
  background: red url(foo.png#sprite);
}

/* build */
.foo {
  background-image: url(sprite.png);
  background-position: 0 0;
}
```
## Keywords

As property order doesn't matter and color keywords are growing, it may be easier to accept any keyword excepting those used by other background properties :
- inherit
### background-attachment
- scroll
- fixed
- local
### background-clip
- border-box
- padding-box
- content-box
### background-position
- top
- bottom
- left
- right
- center
### background-repeat
- repeat-x
- repeat-y
- repeat
- space
- round
- no-repeat
### background-size
- auto
- cover
- contain
### background-image
- none
### hsl(a)

Requires a minor change in regex (or new one) in https://github.com/glebmachine/postcss-easysprites/blob/master/index.js#L473

``` js
// before
var regexes = ['(#([0-9a-f]{3}){1,2})', 'rgba?\\([^\\)]+\\)'];

// after
var regexes = ['(#([0-9a-f]{3}){1,2})', '(rgb|hsl)a?\\([^\\)]+\\)'];
```

Hope it helps !
